name: peacify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.6.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  just_audio: ^0.9.43
  audio_session: ^0.1.23

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboardingpageimage.png
    - assets/images/google.png
    - assets/images/
    - assets/music/
